-- =============================================================================
-- STUFFBOX — Database Schema
-- Supabase / PostgreSQL
-- =============================================================================
-- Canonical schema: run this end-to-end on a fresh Supabase project to get
-- everything (tables, RLS, grants, seeds/triggers). Reflects desired state,
-- not history — incremental changes live in migrations/ (see /migrate skill)
-- and must be mirrored here in the same step.


-- -----------------------------------------------------------------------------
-- Schema
-- -----------------------------------------------------------------------------

create schema if not exists stuffbox;


-- -----------------------------------------------------------------------------
-- Extensions
-- -----------------------------------------------------------------------------
-- pg_trgm: trigram similarity, backing the fuzzy/typo-tolerant name match in
-- stuffbox.search_workspace (word_similarity) and doubling as an ilike
-- '%...%' accelerator for the GIN indexes below.
create extension if not exists pg_trgm;


-- -----------------------------------------------------------------------------
-- ID strategy
-- -----------------------------------------------------------------------------
-- Two kinds of primary key in this schema:
-- - text nanoid(8), generated client-side (JS `nanoid()`) and sent by the app
--   on insert — reserved for the entities that appear directly in app routes
--   and QR deep links: workspaces, locations, moves, items.
-- - uuid, generated by Postgres (`gen_random_uuid()` default) — every other
--   table, the conventional default. profiles is the one exception: its uuid
--   PK is not generated, it mirrors auth.users.id.
--
-- Account provisioning on signup (profile + workspace + owner membership +
-- seeded option_lists) is app code, not a DB trigger — see
-- src/services/provision-account.js. That's also why workspaces.id no longer
-- needs a SQL-side nanoid generator: the client that creates the workspace
-- generates its id, same as every other nanoid table.


-- -----------------------------------------------------------------------------
-- Tablas
-- -----------------------------------------------------------------------------

-- Mirrors auth.users; password never stored here — Supabase Auth owns it
create table stuffbox.profiles (
  uuid            uuid primary key,                    -- = auth.users.id
  name            text not null,
  email           text not null,                        -- mirror, set at signup
  gender          text not null,                         -- random@signup, editable; feeds DiceBear
  avatar_seed     text not null,
  color           text not null default '#e67e22',       -- single color, no light/dark split
  is_super_admin  boolean not null default false,        -- app-wide admin, DB-only editable
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- Collaboration container; auto-created per user on signup
-- id: nanoid(8), client-generated — appears in app/workspace/[id]
create table stuffbox.workspaces (
  id          text primary key,
  name        text not null,
  color       text,                                 -- nullable; falls back to a client-side hash (workspace-color.js) until set
  owner_id    uuid not null references stuffbox.profiles(uuid),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- Owner is also inserted here on workspace creation, so membership is a
-- single check with no special-casing of the owner.
create table stuffbox.workspace_members (
  workspace_id  text not null references stuffbox.workspaces(id) on delete cascade,
  user_id       uuid not null references stuffbox.profiles(uuid),
  joined_at     timestamptz not null default now(),
  primary key (workspace_id, user_id)
);

-- Shareable link, no email flow. id is a plain uuid (never routed by itself —
-- the invite is looked up by `token`, see the RPCs below).
create table stuffbox.workspace_invites (
  id          uuid primary key default gen_random_uuid(),
  workspace_id text not null references stuffbox.workspaces(id) on delete cascade,
  token       text not null unique,
  max_uses    int not null default 1,
  uses_count  int not null default 0,
  expires_at  timestamptz not null default (now() + interval '7 days'),
  invited_by  uuid not null references stuffbox.profiles(uuid),
  created_at  timestamptz not null default now()
);

-- Generic unbounded tree: house/room/closet/shelf/drawer/warehouse/box are
-- all nodes; box = type='box'; multiple roots = multiple houses; boxes nest.
-- active_move_id references moves, created further below — FK added after.
-- id: nanoid(8), client-generated — appears in app/location/[id] and app/l/[id]
create table stuffbox.locations (
  id              text primary key,
  workspace_id    text not null references stuffbox.workspaces(id) on delete cascade,
  parent_id       text references stuffbox.locations(id) on delete cascade,
  name            text not null,
  type            text not null,                         -- free text
  icon            jsonb,                                  -- {library, name}
  lat             double precision,                       -- meaningful on roots for routes
  lng             double precision,
  active_move_id  text,                                   -- set when packed; FK added below
  ai_summary      text,                                   -- cached, regenerable
  is_container    boolean not null default false,          -- defaults true for box/shelf/toolbox/baggage (app-derived from type, not DB-enforced)
  is_item         boolean not null default false,          -- lets this location also appear in the swipe/rate deck, like an item
  description     text,
  is_fragile      boolean not null default false,
  storage_orientation text,                                -- ref option_lists(field='orientation'), no hard FK
  sentimental_value   smallint,                             -- 1-5, hearts
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- Route geometry NOT stored — computed live client-side. The plan's model
-- has origin/destination as root locations (house/warehouse), but that's not
-- DB-enforced — no constraint here blocks e.g. a same-building floor-to-floor
-- move if the app ever wants to allow one.
-- id: nanoid(8), client-generated — appears in app/move/[id]
create table stuffbox.moves (
  id                      text primary key,
  workspace_id            text not null references stuffbox.workspaces(id) on delete cascade,
  name                    text not null,
  origin_location_id      text not null references stuffbox.locations(id),
  destination_location_id text not null references stuffbox.locations(id),
  route_type              text not null default 'land',   -- 'land' | 'air'
  status                  text not null default 'planning', -- app-defined, not DB-constrained
  cost                    numeric,                        -- null = N/A until set via the summary box's edit button
  started_at              date,                            -- set alongside estimated_completion_at when status -> in_transit
  estimated_completion_at date,                            -- the deadline asked for in the same dialog as started_at
  completed_at            date,                            -- auto-set to today when status -> done
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);

alter table stuffbox.locations
  add constraint fk_locations_active_move
  foreign key (active_move_id) references stuffbox.moves(id) on delete set null;

-- id: nanoid(8), client-generated — appears in app/item/[id] and app/i/[id]
create table stuffbox.items (
  id                  text primary key,
  workspace_id        text not null references stuffbox.workspaces(id) on delete cascade,
  location_id         text not null references stuffbox.locations(id) on delete cascade,
  name                text not null,
  description         text,
  quantity            int not null default 1,
  condition           text,                               -- ref option_lists(field='condition'), no hard FK
  sku                 text,
  serial_number       text,
  purchase_price      numeric,
  acquired_month      int,
  acquired_year       int,
  sentimental_value   smallint,                            -- 1-5, hearts
  is_fragile          boolean not null default false,
  storage_orientation text,                                -- ref option_lists(field='orientation'), no hard FK
  icon                jsonb,                                -- own fallback icon
  active_move_id      text references stuffbox.moves(id) on delete set null,  -- loose items only; boxed items inherit their box's move
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

-- Square-masked at render, never physically cropped. id is a plain uuid —
-- never routed by itself, always fetched through its item.
create table stuffbox.item_photos (
  id          uuid primary key default gen_random_uuid(),
  item_id     text not null references stuffbox.items(id) on delete cascade,
  r2_key      text not null,                       -- {workspace_id}/uploads/{photo_id}.jpg
  crop_x      float not null default 0,
  crop_y      float not null default 0,
  zoom        float not null default 1,
  rotation    int not null default 0,              -- degrees: 0/90/180/270, CSS-only like crop_x/crop_y/zoom
  flip_x      boolean not null default false,
  flip_y      boolean not null default false,
  "order"     int not null default 0,
  created_at  timestamptz not null default now()
);

-- id is a plain uuid — never routed by itself
-- Square-masked at render, never physically cropped — same shape as
-- item_photos, just hanging off a location (container-type only, by
-- convention, not DB-enforced) instead of an item.
create table stuffbox.location_photos (
  id          uuid primary key default gen_random_uuid(),
  location_id text not null references stuffbox.locations(id) on delete cascade,
  r2_key      text not null,
  crop_x      float not null default 0,
  crop_y      float not null default 0,
  zoom        float not null default 1,
  rotation    int not null default 0,              -- degrees: 0/90/180/270, CSS-only like crop_x/crop_y/zoom
  flip_x      boolean not null default false,
  flip_y      boolean not null default false,
  "order"     int not null default 0,
  created_at  timestamptz not null default now()
);

create table stuffbox.tags (
  id          uuid primary key default gen_random_uuid(),
  workspace_id text not null references stuffbox.workspaces(id) on delete cascade,
  name        text not null,
  color       text not null,
  icon        jsonb,
  sku         text,
  search_terms text[] not null default '{}',  -- fuzzy-search synonyms, e.g. "instrumentos" -> ["musica"]
  related_icons jsonb not null default '[]'::jsonb,  -- curated [{library,name}] suggested alongside this tag's own icon
  created_at  timestamptz not null default now()
);

create table stuffbox.item_tags (
  item_id  text not null references stuffbox.items(id) on delete cascade,
  tag_id   uuid not null references stuffbox.tags(id) on delete cascade,
  primary key (item_id, tag_id)
);

-- Generic per-workspace configurable lists — one mechanism, not one table per
-- field. id is a plain uuid — never routed by itself.
create table stuffbox.option_lists (
  id          uuid primary key default gen_random_uuid(),
  workspace_id text not null references stuffbox.workspaces(id) on delete cascade,
  field       text not null,                       -- 'condition' | 'orientation'
  value       text not null,
  sort_order  int not null default 0,
  created_at  timestamptz not null default now()
);

-- Settings: 3 DB levels (env + localStorage are the other two); full cascade
-- env < app < workspace < user < localStorage — resolution across levels is
-- deferred to the first real multi-level conflict, not silently assumed.
create table stuffbox.app_settings (
  key         text primary key,
  value       jsonb not null,
  updated_at  timestamptz not null default now()
);

create table stuffbox.workspace_settings (
  workspace_id text not null references stuffbox.workspaces(id) on delete cascade,
  key         text not null,
  value       jsonb not null,
  updated_at  timestamptz not null default now(),
  primary key (workspace_id, key)
);

create table stuffbox.user_settings (
  profile_id  uuid not null references stuffbox.profiles(uuid),
  key         text not null,
  value       jsonb not null,
  updated_at  timestamptz not null default now(),
  primary key (profile_id, key)
);

-- Written by a trigger AFTER UPDATE of location_id/parent_id/active_move_id —
-- not app logic. id is a plain uuid, generated by the trigger's own insert.
create table stuffbox.movement_log (
  id                uuid primary key default gen_random_uuid(),
  workspace_id      text not null references stuffbox.workspaces(id) on delete cascade,
  entity_type       text not null,                 -- 'item' | 'location'
  entity_id         text not null,
  from_location_id  text,
  to_location_id    text,
  move_id           text,
  created_at        timestamptz not null default now()
);

-- Polymorphic like/dislike ratings for the swipe/rate deck — entity_id points
-- to either items or locations (is_item = true), same pattern as
-- movement_log's entity_type/entity_id. Unique per (entity, profile) so a
-- re-swipe upserts the existing vote instead of creating a duplicate.
create table stuffbox.entity_ratings (
  id           uuid primary key default gen_random_uuid(),
  workspace_id text not null references stuffbox.workspaces(id) on delete cascade,
  entity_type  text not null,                       -- 'item' | 'location'
  entity_id    text not null,                        -- no hard FK — see comment above
  profile_id   uuid not null references stuffbox.profiles(uuid) on delete cascade,
  liked        boolean not null,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  unique (entity_type, entity_id, profile_id)
);


-- -----------------------------------------------------------------------------
-- Row Level Security (RLS)
-- -----------------------------------------------------------------------------
-- Since CRUD is direct-from-client, RLS is the actual authorization layer,
-- not decorative. Workspaces are private: visible only to owner or member.

alter table stuffbox.profiles           enable row level security;
alter table stuffbox.workspaces         enable row level security;
alter table stuffbox.workspace_members  enable row level security;
alter table stuffbox.workspace_invites  enable row level security;
alter table stuffbox.locations          enable row level security;
alter table stuffbox.moves              enable row level security;
alter table stuffbox.items              enable row level security;
alter table stuffbox.item_photos        enable row level security;
alter table stuffbox.location_photos    enable row level security;
alter table stuffbox.tags               enable row level security;
alter table stuffbox.item_tags          enable row level security;
alter table stuffbox.option_lists       enable row level security;
alter table stuffbox.app_settings       enable row level security;
alter table stuffbox.workspace_settings enable row level security;
alter table stuffbox.user_settings      enable row level security;
alter table stuffbox.movement_log       enable row level security;
alter table stuffbox.entity_ratings     enable row level security;

-- Helper: is auth.uid() a member (or owner) of this workspace? security
-- definer avoids recursive RLS. Owner is always also a workspace_members row
-- (app code inserts it alongside the workspace itself — see
-- src/services/provision-account.js), so this one check covers both.
create or replace function stuffbox.is_workspace_member(p_workspace_id text, p_user_id uuid)
returns boolean as $$
  select exists (
    select 1 from stuffbox.workspace_members
    where workspace_id = p_workspace_id and user_id = p_user_id
  );
$$ language sql security definer stable;

-- Helper: mirrors bins' requesting_user_is_admin() — security definer stable
create or replace function stuffbox.requesting_user_is_admin()
returns boolean as $$
  select coalesce(
    (select is_super_admin from stuffbox.profiles where uuid = auth.uid()),
    false
  );
$$ language sql security definer stable;

-- Helper: does this workspace's 'collaborationSettings' value allow regular
-- members (not just the owner) to create invite links? Missing key/value
-- coalesces to false — the safe default until an owner explicitly turns it on.
create or replace function stuffbox.workspace_allows_member_invites(p_workspace_id text)
returns boolean as $$
  select coalesce(
    (
      select (value->>'allowMemberInvites')::boolean
      from stuffbox.workspace_settings
      where workspace_id = p_workspace_id and key = 'collaborationSettings'
    ),
    false
  );
$$ language sql security definer stable;

-- Helper: same shape, for "can regular members remove other members?" —
-- removing the owner's own row is still blocked elsewhere regardless of this
-- setting (see the workspace_members delete policy below).
create or replace function stuffbox.workspace_allows_member_removal(p_workspace_id text)
returns boolean as $$
  select coalesce(
    (
      select (value->>'allowMemberRemove')::boolean
      from stuffbox.workspace_settings
      where workspace_id = p_workspace_id and key = 'collaborationSettings'
    ),
    false
  );
$$ language sql security definer stable;

-- Helper: same shape, for "can regular members edit the non-collaboration
-- settings (name/color, map default)?" — the collaboration section itself
-- and deleting the workspace stay owner-only regardless of this setting.
create or replace function stuffbox.workspace_allows_member_edit_settings(p_workspace_id text)
returns boolean as $$
  select coalesce(
    (
      select (value->>'allowMemberEditSettings')::boolean
      from stuffbox.workspace_settings
      where workspace_id = p_workspace_id and key = 'collaborationSettings'
    ),
    false
  );
$$ language sql security definer stable;

-- profiles
create policy "profiles: self access"
  on stuffbox.profiles for select
  using (uuid = auth.uid());

create policy "profiles: shared workspace visibility"
  on stuffbox.profiles for select
  using (
    exists (
      select 1
      from stuffbox.workspace_members mine
      join stuffbox.workspace_members theirs on theirs.workspace_id = mine.workspace_id
      where mine.user_id = auth.uid() and theirs.user_id = profiles.uuid
    )
  );

create policy "profiles: admin full access"
  on stuffbox.profiles for all
  using (stuffbox.requesting_user_is_admin())
  with check (stuffbox.requesting_user_is_admin());

create policy "profiles: owner can insert"
  on stuffbox.profiles for insert
  with check (uuid = auth.uid());

create policy "profiles: owner can update"
  on stuffbox.profiles for update
  using (uuid = auth.uid())
  with check (uuid = auth.uid() and is_super_admin = false);

-- workspaces (member WITH CHECK also allows owner_id = auth.uid() so the
-- owner can insert the very first row, before any workspace_members exists;
-- deleting the entire workspace, which cascades to everything it contains,
-- is owner-only; updating is owner-only unless collaborationSettings.
-- allowMemberEditSettings opts regular members in — select/insert stay open
-- to any member as before)
create policy "workspaces: member select"
  on stuffbox.workspaces for select
  using (stuffbox.is_workspace_member(id, auth.uid()));

create policy "workspaces: member insert"
  on stuffbox.workspaces for insert
  with check (owner_id = auth.uid() or stuffbox.is_workspace_member(id, auth.uid()));

create policy "workspaces: owner or allowed member update"
  on stuffbox.workspaces for update
  using (stuffbox.is_workspace_member(id, auth.uid()))
  with check (
    owner_id = auth.uid()
    or (
      stuffbox.is_workspace_member(id, auth.uid())
      and stuffbox.workspace_allows_member_edit_settings(id)
    )
  );

create policy "workspaces: owner delete"
  on stuffbox.workspaces for delete
  using (owner_id = auth.uid());

create policy "workspaces: admin full access"
  on stuffbox.workspaces for all
  using (stuffbox.requesting_user_is_admin())
  with check (stuffbox.requesting_user_is_admin());

-- workspace_members (insert allows self-join, which is only reachable via a
-- valid claim_workspace_invite() call — see RPCs below; delete restricted to
-- the workspace owner or the member removing themself, per the plan — and no
-- clause below may ever target the owner's own row: an owner can only leave
-- by deleting the whole workspace, never by deleting their own membership)
create policy "workspace_members: member select"
  on stuffbox.workspace_members for select
  using (stuffbox.is_workspace_member(workspace_id, auth.uid()));

create policy "workspace_members: self insert"
  on stuffbox.workspace_members for insert
  with check (user_id = auth.uid());

-- owner, self, or (when the workspace's collaborationSettings.allowMemberRemove
-- is on) any other member removing someone who isn't the owner
create policy "workspace_members: owner, self, or allowed member delete"
  on stuffbox.workspace_members for delete
  using (
    not exists (
      select 1 from stuffbox.workspaces w
      where w.id = workspace_id and w.owner_id = workspace_members.user_id
    )
    and (
      user_id = auth.uid()
      or exists (
        select 1 from stuffbox.workspaces w
        where w.id = workspace_id and w.owner_id = auth.uid()
      )
      or (
        stuffbox.workspace_allows_member_removal(workspace_id)
        and stuffbox.is_workspace_member(workspace_id, auth.uid())
      )
    )
  );

create policy "workspace_members: admin full access"
  on stuffbox.workspace_members for all
  using (stuffbox.requesting_user_is_admin())
  with check (stuffbox.requesting_user_is_admin());

-- workspace_invites (no public select — a stranger following a link isn't a
-- member yet; the read-only landing and the join both go through the
-- security-definer RPCs below, which expose only the single row for the
-- exact token supplied, never the table). Deleting an invite is owner-only
-- no matter what; creating one can be relaxed to regular members via
-- collaborationSettings.allowMemberInvites.
create policy "workspace_invites: member select"
  on stuffbox.workspace_invites for select
  using (stuffbox.is_workspace_member(workspace_id, auth.uid()));

create policy "workspace_invites: owner or allowed member insert"
  on stuffbox.workspace_invites for insert
  with check (
    stuffbox.is_workspace_member(workspace_id, auth.uid())
    and (
      exists (
        select 1 from stuffbox.workspaces w
        where w.id = workspace_id and w.owner_id = auth.uid()
      )
      or stuffbox.workspace_allows_member_invites(workspace_id)
    )
  );

create policy "workspace_invites: owner delete"
  on stuffbox.workspace_invites for delete
  using (
    exists (
      select 1 from stuffbox.workspaces w
      where w.id = workspace_id and w.owner_id = auth.uid()
    )
  );

create policy "workspace_invites: admin full access"
  on stuffbox.workspace_invites for all
  using (stuffbox.requesting_user_is_admin())
  with check (stuffbox.requesting_user_is_admin());

-- locations
create policy "locations: member access"
  on stuffbox.locations for all
  using (stuffbox.is_workspace_member(workspace_id, auth.uid()))
  with check (stuffbox.is_workspace_member(workspace_id, auth.uid()));

create policy "locations: admin full access"
  on stuffbox.locations for all
  using (stuffbox.requesting_user_is_admin())
  with check (stuffbox.requesting_user_is_admin());

-- moves
create policy "moves: member access"
  on stuffbox.moves for all
  using (stuffbox.is_workspace_member(workspace_id, auth.uid()))
  with check (stuffbox.is_workspace_member(workspace_id, auth.uid()));

create policy "moves: admin full access"
  on stuffbox.moves for all
  using (stuffbox.requesting_user_is_admin())
  with check (stuffbox.requesting_user_is_admin());

-- items
create policy "items: member access"
  on stuffbox.items for all
  using (stuffbox.is_workspace_member(workspace_id, auth.uid()))
  with check (stuffbox.is_workspace_member(workspace_id, auth.uid()));

create policy "items: admin full access"
  on stuffbox.items for all
  using (stuffbox.requesting_user_is_admin())
  with check (stuffbox.requesting_user_is_admin());

-- item_photos (no workspace_id column — scoped through items)
create policy "item_photos: member access"
  on stuffbox.item_photos for all
  using (
    exists (
      select 1 from stuffbox.items i
      where i.id = item_id and stuffbox.is_workspace_member(i.workspace_id, auth.uid())
    )
  )
  with check (
    exists (
      select 1 from stuffbox.items i
      where i.id = item_id and stuffbox.is_workspace_member(i.workspace_id, auth.uid())
    )
  );

create policy "item_photos: admin full access"
  on stuffbox.item_photos for all
  using (stuffbox.requesting_user_is_admin())
  with check (stuffbox.requesting_user_is_admin());

-- location_photos (no workspace_id column — scoped through locations)
create policy "location_photos: member access"
  on stuffbox.location_photos for all
  using (
    exists (
      select 1 from stuffbox.locations l
      where l.id = location_id and stuffbox.is_workspace_member(l.workspace_id, auth.uid())
    )
  )
  with check (
    exists (
      select 1 from stuffbox.locations l
      where l.id = location_id and stuffbox.is_workspace_member(l.workspace_id, auth.uid())
    )
  );

create policy "location_photos: admin full access"
  on stuffbox.location_photos for all
  using (stuffbox.requesting_user_is_admin())
  with check (stuffbox.requesting_user_is_admin());

-- tags
create policy "tags: member access"
  on stuffbox.tags for all
  using (stuffbox.is_workspace_member(workspace_id, auth.uid()))
  with check (stuffbox.is_workspace_member(workspace_id, auth.uid()));

create policy "tags: admin full access"
  on stuffbox.tags for all
  using (stuffbox.requesting_user_is_admin())
  with check (stuffbox.requesting_user_is_admin());

-- item_tags (no workspace_id column — scoped through items)
create policy "item_tags: member access"
  on stuffbox.item_tags for all
  using (
    exists (
      select 1 from stuffbox.items i
      where i.id = item_id and stuffbox.is_workspace_member(i.workspace_id, auth.uid())
    )
  )
  with check (
    exists (
      select 1 from stuffbox.items i
      where i.id = item_id and stuffbox.is_workspace_member(i.workspace_id, auth.uid())
    )
  );

create policy "item_tags: admin full access"
  on stuffbox.item_tags for all
  using (stuffbox.requesting_user_is_admin())
  with check (stuffbox.requesting_user_is_admin());

-- option_lists
create policy "option_lists: member access"
  on stuffbox.option_lists for all
  using (stuffbox.is_workspace_member(workspace_id, auth.uid()))
  with check (stuffbox.is_workspace_member(workspace_id, auth.uid()));

create policy "option_lists: admin full access"
  on stuffbox.option_lists for all
  using (stuffbox.requesting_user_is_admin())
  with check (stuffbox.requesting_user_is_admin());

-- app_settings: SELECT = any authenticated (client must read it to apply
-- config); writes admin only. Admin-only UI visibility is frontend-only.
create policy "app_settings: any authenticated can select"
  on stuffbox.app_settings for select
  using (true);

create policy "app_settings: admin can write"
  on stuffbox.app_settings for all
  using (stuffbox.requesting_user_is_admin())
  with check (stuffbox.requesting_user_is_admin());

-- workspace_settings (the 'collaborationSettings' key is owner-write-only —
-- otherwise any member could grant themselves the permissions it controls
-- directly via the API, bypassing the settings-page owner gate; every other
-- key, e.g. mapDefaultViewport, is owner-writable or, when
-- collaborationSettings.allowMemberEditSettings is on, member-writable too)
create policy "workspace_settings: member select"
  on stuffbox.workspace_settings for select
  using (stuffbox.is_workspace_member(workspace_id, auth.uid()));

create policy "workspace_settings: owner or allowed member write other keys"
  on stuffbox.workspace_settings for insert
  with check (
    key <> 'collaborationSettings'
    and (
      exists (
        select 1 from stuffbox.workspaces w
        where w.id = workspace_id and w.owner_id = auth.uid()
      )
      or (
        stuffbox.is_workspace_member(workspace_id, auth.uid())
        and stuffbox.workspace_allows_member_edit_settings(workspace_id)
      )
    )
  );

create policy "workspace_settings: owner or allowed member update other keys"
  on stuffbox.workspace_settings for update
  using (
    stuffbox.is_workspace_member(workspace_id, auth.uid())
    and key <> 'collaborationSettings'
  )
  with check (
    key <> 'collaborationSettings'
    and (
      exists (
        select 1 from stuffbox.workspaces w
        where w.id = workspace_id and w.owner_id = auth.uid()
      )
      or (
        stuffbox.is_workspace_member(workspace_id, auth.uid())
        and stuffbox.workspace_allows_member_edit_settings(workspace_id)
      )
    )
  );

create policy "workspace_settings: owner write collaboration key"
  on stuffbox.workspace_settings for insert
  with check (
    key = 'collaborationSettings'
    and exists (
      select 1 from stuffbox.workspaces w
      where w.id = workspace_id and w.owner_id = auth.uid()
    )
  );

create policy "workspace_settings: owner update collaboration key"
  on stuffbox.workspace_settings for update
  using (
    key = 'collaborationSettings'
    and exists (
      select 1 from stuffbox.workspaces w
      where w.id = workspace_id and w.owner_id = auth.uid()
    )
  )
  with check (
    key = 'collaborationSettings'
    and exists (
      select 1 from stuffbox.workspaces w
      where w.id = workspace_id and w.owner_id = auth.uid()
    )
  );

create policy "workspace_settings: admin full access"
  on stuffbox.workspace_settings for all
  using (stuffbox.requesting_user_is_admin())
  with check (stuffbox.requesting_user_is_admin());

-- user_settings
create policy "user_settings: self access"
  on stuffbox.user_settings for all
  using (profile_id = auth.uid())
  with check (profile_id = auth.uid());

create policy "user_settings: admin full access"
  on stuffbox.user_settings for all
  using (stuffbox.requesting_user_is_admin())
  with check (stuffbox.requesting_user_is_admin());

-- movement_log: read-only for members (it's written by a trigger, not app
-- logic — no member insert/update/delete policy is granted on purpose)
create policy "movement_log: member select"
  on stuffbox.movement_log for select
  using (stuffbox.is_workspace_member(workspace_id, auth.uid()));

create policy "movement_log: admin full access"
  on stuffbox.movement_log for all
  using (stuffbox.requesting_user_is_admin())
  with check (stuffbox.requesting_user_is_admin());

-- entity_ratings
create policy "entity_ratings: member access"
  on stuffbox.entity_ratings for all
  using (stuffbox.is_workspace_member(workspace_id, auth.uid()))
  with check (stuffbox.is_workspace_member(workspace_id, auth.uid()));

create policy "entity_ratings: admin full access"
  on stuffbox.entity_ratings for all
  using (stuffbox.requesting_user_is_admin())
  with check (stuffbox.requesting_user_is_admin());


-- -----------------------------------------------------------------------------
-- Invite RPCs
-- -----------------------------------------------------------------------------
-- Mirrors bins' get_bin_access(): a security-definer RPC lets a non-member
-- resolve a single invite by its (unguessable) token without a public SELECT
-- policy that would expose every workspace's invites to any authenticated user.

-- Read-only landing check (app/invite/[token] — bot-safe, no side effects)
create or replace function stuffbox.get_invite_by_token(p_token text)
returns table(invite_id text, workspace_id text, workspace_name text, valid boolean)
security definer stable language sql as $$
  select
    i.id,
    i.workspace_id,
    w.name,
    (i.uses_count < i.max_uses and now() < i.expires_at)
  from stuffbox.workspace_invites i
  join stuffbox.workspaces w on w.id = i.workspace_id
  where i.token = p_token;
$$;

-- "Unirse" — atomic claim (increment + validity check in one statement) then join
create or replace function stuffbox.claim_workspace_invite(p_token text)
returns table(workspace_id text)
security definer language plpgsql as $$
declare
  v_workspace_id text;
begin
  update stuffbox.workspace_invites
  set uses_count = uses_count + 1
  where token = p_token
    and uses_count < max_uses
    and now() < expires_at
  returning stuffbox.workspace_invites.workspace_id into v_workspace_id;

  if v_workspace_id is null then
    raise exception 'Invite is invalid, expired, or exhausted';
  end if;

  insert into stuffbox.workspace_members (workspace_id, user_id)
  values (v_workspace_id, auth.uid())
  on conflict do nothing;

  return query select v_workspace_id;
end;
$$;

grant execute on function stuffbox.get_invite_by_token(text) to authenticated;
grant execute on function stuffbox.claim_workspace_invite(text) to authenticated;

-- A fresh visitor following an /invite/[token] link has no session yet, so
-- the landing lookup above runs as anon — needs its own narrow grant rather
-- than the blanket authenticated/service_role one below. claim stays
-- authenticated-only: it never runs until after the OTP verify establishes
-- a session.
grant execute on function stuffbox.get_invite_by_token(text) to anon;

-- Same reasoning as get_invite_by_token above: the register/invite email
-- step needs to recognize an existing account and reflect its saved
-- identity in the UI before any session exists — read-only, no writes to
-- profiles, so a narrow anon grant is safe.
create or replace function stuffbox.get_profile_identity_by_email(p_email text)
returns table(name text, gender text, avatar_seed text, color text)
security definer stable language sql as $$
  select p.name, p.gender, p.avatar_seed, p.color
  from stuffbox.profiles p
  where p.email = p_email;
$$;

grant execute on function stuffbox.get_profile_identity_by_email(text) to authenticated;
grant execute on function stuffbox.get_profile_identity_by_email(text) to anon;


-- -----------------------------------------------------------------------------
-- Location price rollup
-- -----------------------------------------------------------------------------
-- Recursive sum of purchase_price across every item in a location's subtree
-- (nested boxes included, any depth). Plain invoker rights (no security
-- definer) — the underlying RLS on locations/items already scopes this to
-- what the caller can see, so an out-of-workspace id just sums to 0 instead
-- of leaking anything.

create or replace function stuffbox.location_total_price(p_location_id text)
returns numeric
language sql
stable
as $$
  with recursive subtree as (
    select id from stuffbox.locations where id = p_location_id
    union all
    select l.id from stuffbox.locations l
    join subtree s on l.parent_id = s.id
  )
  select coalesce(sum(i.purchase_price), 0)
  from stuffbox.items i
  where i.location_id in (select id from subtree);
$$;

grant execute on function stuffbox.location_total_price(text) to authenticated;

-- Same recursive subtree as location_total_price above, but a plain item
-- count (nested boxes included, any depth) instead of a price sum — used by
-- the location detail page's stat row.
create or replace function stuffbox.location_item_count(p_location_id text)
returns bigint
language sql
stable
as $$
  with recursive subtree as (
    select id from stuffbox.locations where id = p_location_id
    union all
    select l.id from stuffbox.locations l
    join subtree s on l.parent_id = s.id
  )
  select count(*)
  from stuffbox.items i
  where i.location_id in (select id from subtree);
$$;

grant execute on function stuffbox.location_item_count(text) to authenticated;

-- Same pattern as location_total_price above (recursive subtree), but seeded
-- from every location flagged into this move (not a single location id),
-- plus loose items packed directly into the move — boxed items inherit
-- their box's move state so they never carry active_move_id themselves (see
-- packedInMoveQuery, src/queries/moves.js).
create or replace function stuffbox.move_total_value(p_move_id text)
returns numeric
language sql
stable
as $$
  with recursive subtree as (
    select id from stuffbox.locations where active_move_id = p_move_id
    union all
    select l.id from stuffbox.locations l
    join subtree s on l.parent_id = s.id
  )
  select
    coalesce((select sum(i.purchase_price) from stuffbox.items i where i.active_move_id = p_move_id), 0)
    + coalesce((select sum(i.purchase_price) from stuffbox.items i where i.location_id in (select id from subtree)), 0);
$$;

grant execute on function stuffbox.move_total_value(text) to authenticated;


-- -----------------------------------------------------------------------------
-- Workspace search
-- -----------------------------------------------------------------------------
-- Resolves only the ordered (kind, id) pairs + total_count for a workspace
-- search — the one thing that needs real SQL (union across two tables, a
-- recursive ancestor walk for the house filter, and a single shared count).
-- The app fetches full item/location rows for this page's ids separately via
-- plain direct-client selects (same shape as itemsAtLocationQuery /
-- locationChildrenQuery), so search results carry the same photos/tags/
-- fields as their native list views instead of a stripped-down shape.
--
-- Plain invoker rights (no security definer), same pattern as
-- location_total_price above — RLS on locations/items already scopes this to
-- what the caller can see. Type only applies to locations (items have no
-- `type` column) and tags only apply to items (locations have no tags), so
-- each side excludes itself entirely when the other's filter is active.
--
-- Name matching combines exact substring (ilike) with pg_trgm word_similarity
-- for typo tolerance ("macbuc" → "MacBook") — ilike stays as the guaranteed
-- match (trigram similarity is unreliable for very short queries like SKUs),
-- word_similarity only adds the fuzzy net on top. word_similarity (not plain
-- similarity) because it scores the best-matching word/substring within the
-- name rather than the whole string, since names are usually longer than the
-- query. Results rank by word_similarity when a query is present, else by
-- name (plain alphabetical browse). Items also match on sku, ilike-only (no
-- word_similarity) per the same short-query unreliability noted above.
create or replace function stuffbox.search_workspace(
  p_workspace_id text,
  p_query        text default null,
  p_tag_ids      uuid[] default null,
  p_type_ids     text[] default null,
  p_packed       boolean default null,
  p_house_ids    text[] default null,
  p_limit        int default 25,
  p_offset       int default 0
)
returns table (
  kind             text,
  id               text,
  effective_move_id text,
  move_owner_kind  text,
  total_count      bigint
)
language sql
stable
as $$
  -- location_roots also carries `effective_move_id` top-down: the nearest
  -- packed ancestor's active_move_id (own value wins), same inheritance rule
  -- as src/helpers/moves.js getInheritedPackedMoveId — boxed items/locations
  -- don't carry their own active_move_id, only the box that was actually
  -- packed does.
  with recursive location_roots as (
    select l.id, l.id as root_id, l.active_move_id as effective_move_id
    from stuffbox.locations l
    where l.parent_id is null and l.workspace_id = p_workspace_id
    union all
    select l.id, lr.root_id, coalesce(l.active_move_id, lr.effective_move_id)
    from stuffbox.locations l
    join location_roots lr on l.parent_id = lr.id
    where l.workspace_id = p_workspace_id
  ),
  matched_locations as (
    select
      'location'::text as kind,
      l.id,
      l.name,
      lr.effective_move_id,
      -- Always 'location' when packed — a location's own active_move_id and
      -- every one of its ancestors are locations too.
      (case when lr.effective_move_id is not null then 'location' end)::text as move_owner_kind
    from stuffbox.locations l
    join location_roots lr on lr.id = l.id
    where l.workspace_id = p_workspace_id
      and p_tag_ids is null
      and (
        p_query is null
        or l.name ilike '%' || p_query || '%'
        or word_similarity(p_query, l.name) > 0.3
      )
      and (p_type_ids is null or l.type = any(p_type_ids))
      and (p_packed is null or (lr.effective_move_id is not null) = p_packed)
      and (p_house_ids is null or lr.root_id = any(p_house_ids))
  ),
  matched_items as (
    select
      'item'::text as kind,
      i.id,
      i.name,
      coalesce(i.active_move_id, lr.effective_move_id) as effective_move_id,
      -- 'item' when the item itself is loose-packed, 'location' when it's
      -- only packed because a containing box is.
      (case
         when i.active_move_id is not null then 'item'
         when lr.effective_move_id is not null then 'location'
       end)::text as move_owner_kind
    from stuffbox.items i
    join location_roots lr on lr.id = i.location_id
    where i.workspace_id = p_workspace_id
      and p_type_ids is null
      and (
        p_query is null
        or i.name ilike '%' || p_query || '%'
        or word_similarity(p_query, i.name) > 0.3
        or i.sku ilike '%' || p_query || '%'
      )
      and (
        p_packed is null
        or (coalesce(i.active_move_id, lr.effective_move_id) is not null) = p_packed
      )
      and (p_house_ids is null or lr.root_id = any(p_house_ids))
      and (
        p_tag_ids is null
        or exists (
          select 1 from stuffbox.item_tags it
          where it.item_id = i.id and it.tag_id = any(p_tag_ids)
        )
      )
  ),
  combined as (
    select * from matched_locations
    union all
    select * from matched_items
  )
  select c.kind, c.id, c.effective_move_id, c.move_owner_kind, count(*) over() as total_count
  from combined c
  order by
    case when p_query is not null then word_similarity(p_query, c.name) end desc nulls last,
    c.name
  limit p_limit offset p_offset;
$$;

grant execute on function stuffbox.search_workspace(text, text, uuid[], text[], boolean, text[], int, int) to authenticated;


-- -----------------------------------------------------------------------------
-- Item → location conversion
-- -----------------------------------------------------------------------------
-- "Promote an item to a location" — item edit screen action. Runs as one
-- plpgsql transaction so the item is never lost between steps: create the
-- location (as a sibling inside the item's current container), copy its
-- photos over, then delete it. Plain invoker rights (no security definer),
-- same reasoning as location_total_price/search_workspace above — RLS on
-- items/locations/location_photos already scopes every statement here to
-- what the calling user can see/write. is_container is passed in (computed
-- client-side via isContainerType, same as createLocationMutation/
-- updateLocationMutation) rather than re-derived from p_type in SQL.
-- is_item is always forced true so the promoted location keeps showing up
-- in the swipe/rate deck, same as the item did. Tags don't carry over —
-- there's no location_tags equivalent; item_tags cascades away with the item.
create or replace function stuffbox.convert_item_to_location(
  p_item_id      text,
  p_location_id  text,
  p_type         text,
  p_is_container boolean
)
returns stuffbox.locations
language plpgsql
as $$
declare
  v_item     stuffbox.items;
  v_location stuffbox.locations;
begin
  select * into v_item from stuffbox.items where id = p_item_id;
  if not found then
    raise exception 'item % not found', p_item_id;
  end if;

  insert into stuffbox.locations (
    id, workspace_id, parent_id, name, type, icon, active_move_id,
    is_container, is_item, description, is_fragile, storage_orientation,
    sentimental_value
  ) values (
    p_location_id, v_item.workspace_id, v_item.location_id, v_item.name, p_type,
    v_item.icon, v_item.active_move_id, p_is_container, true, v_item.description,
    v_item.is_fragile, v_item.storage_orientation, v_item.sentimental_value
  )
  returning * into v_location;

  insert into stuffbox.location_photos (
    location_id, r2_key, crop_x, crop_y, zoom, rotation, flip_x, flip_y, "order"
  )
  select p_location_id, r2_key, crop_x, crop_y, zoom, rotation, flip_x, flip_y, "order"
  from stuffbox.item_photos
  where item_id = p_item_id;

  delete from stuffbox.items where id = p_item_id;

  return v_location;
end;
$$;

grant execute on function stuffbox.convert_item_to_location(text, text, text, boolean) to authenticated;


-- -----------------------------------------------------------------------------
-- Triggers
-- -----------------------------------------------------------------------------
-- Account provisioning (profile + workspace + owner membership + seeded
-- option_lists) is NOT here — it's app code. See src/services/provision-account.js.
-- No structural validation on moves either (e.g. "endpoints must be roots") —
-- that's a mutationFn's job if/when it's actually needed. What's left is only
-- the audit log, which has to hold regardless of which code path wrote the row.

-- movement_log: written on item location/move changes, never by app logic.
-- security definer — movement_log has no member INSERT policy on purpose
-- (read-only for members), so the trigger itself needs elevated rights to
-- write the audit row regardless of the calling user's own grants.
create or replace function stuffbox.log_item_movement()
returns trigger
language plpgsql
security definer
as $$
begin
  if NEW.location_id is distinct from OLD.location_id
     or NEW.active_move_id is distinct from OLD.active_move_id then
    insert into stuffbox.movement_log
      (workspace_id, entity_type, entity_id, from_location_id, to_location_id, move_id)
    values
      (NEW.workspace_id, 'item', NEW.id, OLD.location_id, NEW.location_id, NEW.active_move_id);
  end if;
  return NEW;
end;
$$;

create trigger on_item_location_change
  after update on stuffbox.items
  for each row execute function stuffbox.log_item_movement();

-- movement_log: written on location parent/move changes (transfer/pack/unpack)
-- security definer — same reason as log_item_movement() above.
create or replace function stuffbox.log_location_movement()
returns trigger
language plpgsql
security definer
as $$
begin
  if NEW.parent_id is distinct from OLD.parent_id
     or NEW.active_move_id is distinct from OLD.active_move_id then
    insert into stuffbox.movement_log
      (workspace_id, entity_type, entity_id, from_location_id, to_location_id, move_id)
    values
      (NEW.workspace_id, 'location', NEW.id, OLD.parent_id, NEW.parent_id, NEW.active_move_id);
  end if;
  return NEW;
end;
$$;

create trigger on_location_parent_change
  after update on stuffbox.locations
  for each row execute function stuffbox.log_location_movement();


-- -----------------------------------------------------------------------------
-- Índices
-- -----------------------------------------------------------------------------

create index if not exists idx_workspaces_owner_id           on stuffbox.workspaces (owner_id);
create index if not exists idx_workspace_members_user_id      on stuffbox.workspace_members (user_id);
create index if not exists idx_workspace_invites_workspace_id on stuffbox.workspace_invites (workspace_id);
create index if not exists idx_locations_workspace_id         on stuffbox.locations (workspace_id);
create index if not exists idx_locations_parent_id            on stuffbox.locations (parent_id);
create index if not exists idx_locations_active_move_id       on stuffbox.locations (active_move_id);
create index if not exists idx_moves_workspace_id             on stuffbox.moves (workspace_id);
create index if not exists idx_items_workspace_id             on stuffbox.items (workspace_id);
create index if not exists idx_items_location_id              on stuffbox.items (location_id);
create index if not exists idx_items_active_move_id           on stuffbox.items (active_move_id);
create index if not exists idx_item_photos_item_id            on stuffbox.item_photos (item_id);
create index if not exists idx_location_photos_location_id    on stuffbox.location_photos (location_id);
create index if not exists idx_tags_workspace_id              on stuffbox.tags (workspace_id);
create index if not exists idx_option_lists_workspace_field   on stuffbox.option_lists (workspace_id, field);
create index if not exists idx_movement_log_workspace_id      on stuffbox.movement_log (workspace_id);
create index if not exists idx_entity_ratings_workspace_id    on stuffbox.entity_ratings (workspace_id);
create index if not exists idx_entity_ratings_entity          on stuffbox.entity_ratings (entity_type, entity_id);
create index if not exists idx_entity_ratings_profile_id      on stuffbox.entity_ratings (profile_id);
create index if not exists idx_profiles_is_super_admin        on stuffbox.profiles (is_super_admin);

-- Trigram GIN indexes — back the fuzzy name match in search_workspace and
-- double as an ilike '%...%' accelerator (pg_trgm's documented use case).
create index if not exists idx_locations_name_trgm on stuffbox.locations using gin (name gin_trgm_ops);
create index if not exists idx_items_name_trgm     on stuffbox.items using gin (name gin_trgm_ops);
create index if not exists idx_items_sku_trgm      on stuffbox.items using gin (sku gin_trgm_ops);


-- -----------------------------------------------------------------------------
-- Grants
-- -----------------------------------------------------------------------------
-- No blanket anon grants — zero public content (unlike bins). anon only
-- gets schema USAGE (required just to resolve the schema-qualified function
-- name via PostgREST) plus the one narrow EXECUTE grant above
-- (get_invite_by_token) — no ALL ON TABLES/ROUTINES/SEQUENCES for anon.

GRANT USAGE ON SCHEMA stuffbox TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA stuffbox TO authenticated, service_role;
GRANT ALL ON ALL ROUTINES IN SCHEMA stuffbox TO authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA stuffbox TO authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA stuffbox GRANT ALL ON TABLES TO authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA stuffbox GRANT ALL ON ROUTINES TO authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA stuffbox GRANT ALL ON SEQUENCES TO authenticated, service_role;
